/**
 * Words in Context items — the largest single skill in Craft and Structure.
 *
 * Each item gives a short passage with one blank and asks which word or phrase
 * "most logically completes the text." Distractors are chosen to be plausible in
 * register but wrong in sense: they are words a test taker might associate with
 * the topic, not obviously unsuitable ones.
 */
import { Rng } from "../rng";
import { ORIGINAL, type ItemBody, type Template } from "../types";
import { buildChoices } from "../util";
import type { Difficulty } from "../../../src/lib/sat/types";

const base = { subject: "rw", domain: "craft-and-structure", source: ORIGINAL } as const;

interface VocabSeed {
  text: string;
  answer: string;
  wrong: [string, string, string];
  why: string;
  difficulty: Difficulty;
  /** Some items ask for a phrase rather than a single word. */
  phrase?: boolean;
}

const SEEDS: VocabSeed[] = [
  {
    text: "Marine biologist Ayanna Fields has spent two decades studying octopus cognition. Her results have been ______ by other laboratories, which have repeatedly obtained the same problem-solving behavior using her published protocols.",
    answer: "corroborated",
    wrong: ["complicated", "anticipated", "circulated"],
    why: "The clause after the comma says other labs obtained the same results, which *confirms* Fields's findings. *Corroborated* means confirmed by additional evidence.",
    difficulty: "medium",
  },
  {
    text: "Far from being a ______ figure in the movement, Bessie Coleman was central to it: she trained a generation of aviators and drew crowds of thousands to her exhibitions.",
    answer: "peripheral",
    wrong: ["celebrated", "controversial", "prolific"],
    why: "*Far from being ___, she was central* sets up a contrast with *central*. *Peripheral* means at the edge, the opposite of central.",
    difficulty: "medium",
  },
  {
    text: "The committee's report was deliberately ______: rather than recommending a single course of action, it laid out four options and declined to rank them.",
    answer: "noncommittal",
    wrong: ["exhaustive", "inflammatory", "concise"],
    why: "The colon explains that the report refused to recommend or rank. *Noncommittal* describes exactly that refusal to take a position.",
    difficulty: "hard",
  },
  {
    text: "Although the storm was forecast three days in advance, the town's response was ______; crews were still sandbagging the riverfront when the water arrived.",
    answer: "belated",
    wrong: ["decisive", "methodical", "elaborate"],
    why: "The semicolon shows crews were still working when the flood came — the response came too late. *Belated* means delayed past the proper time.",
    difficulty: "medium",
  },
  {
    text: "Cartographer Sofia Renn's maps are admired for their ______: every coastline, road, and elevation line is drawn to a tolerance of a few meters.",
    answer: "precision",
    wrong: ["novelty", "austerity", "ambition"],
    why: "The colon explains that everything is drawn to a tight tolerance, which is a description of exactness. *Precision* names that quality.",
    difficulty: "easy",
  },
  {
    text: "The novel's plot is famously ______, doubling back on itself so often that many readers keep a diagram of the timeline as they read.",
    answer: "convoluted",
    wrong: ["derivative", "sentimental", "understated"],
    why: "Doubling back so often that readers need a diagram describes something twisted and hard to follow. *Convoluted* means exactly that.",
    difficulty: "medium",
  },
  {
    text: "Early accounts of the migration were ______, based largely on the recollections of a handful of travelers rather than on systematic observation.",
    answer: "anecdotal",
    wrong: ["quantitative", "exhaustive", "clandestine"],
    why: "The sentence contrasts individual recollections with systematic observation. *Anecdotal* describes evidence drawn from scattered personal reports.",
    difficulty: "medium",
  },
  {
    text: "Rather than settling the question, the new radiocarbon dates ______ it: two of the samples returned ages four centuries apart.",
    answer: "muddied",
    wrong: ["resolved", "postponed", "documented"],
    why: "*Rather than settling* signals the opposite of resolution, and the conflicting dates confuse matters. *Muddied* means made unclear.",
    difficulty: "hard",
  },
  {
    text: "The architect's later buildings are notably ______ compared with her early work: the ornament is stripped away, and the structural frame is left visible.",
    answer: "austere",
    wrong: ["ornate", "derivative", "provisional"],
    why: "Stripped ornament and an exposed frame describe severe plainness. *Austere* means plain and unadorned.",
    difficulty: "medium",
  },
  {
    text: "Because the tunnel would pass beneath a protected aquifer, engineers were required to demonstrate that their method posed no ______ risk of contamination.",
    answer: "appreciable",
    wrong: ["arbitrary", "hypothetical", "reciprocal"],
    why: "The engineers must show the risk is not large enough to matter. *Appreciable* means large enough to be noticed or measured.",
    difficulty: "hard",
  },
  {
    text: "Ellsworth's essays are ______ in their range, moving in a single paragraph from glacial geology to eighteenth-century opera.",
    answer: "expansive",
    wrong: ["parochial", "tentative", "repetitive"],
    why: "Moving from geology to opera in one paragraph shows very wide coverage. *Expansive* means broad in scope.",
    difficulty: "medium",
  },
  {
    text: "The treaty's language was left intentionally ______ so that each government could present the agreement to its own citizens as a victory.",
    answer: "ambiguous",
    wrong: ["ceremonial", "binding", "abbreviated"],
    why: "Language that lets two sides claim opposite readings is open to more than one interpretation. *Ambiguous* names that property.",
    difficulty: "medium",
  },
  {
    text: "What appears at first to be a ______ arrangement of stones turns out, when mapped, to follow the axis of the midwinter sunrise almost exactly.",
    answer: "haphazard",
    wrong: ["ceremonial", "monumental", "ancient"],
    why: "The sentence contrasts a first impression with a precise underlying pattern, so the blank must mean disorganized. *Haphazard* means lacking order.",
    difficulty: "medium",
  },
  {
    text: "Chemist Rosalind Nakata is ______ about the timeline: she expects a working prototype within three years, a target most of her colleagues consider optimistic.",
    answer: "sanguine",
    wrong: ["evasive", "indifferent", "meticulous"],
    why: "She expects success sooner than colleagues think reasonable, so she is confidently hopeful. *Sanguine* means optimistic.",
    difficulty: "hard",
  },
  {
    text: "The restoration was ______ rather than transformative: the conservators stabilized the plaster and cleaned the surface but changed nothing that a visitor would notice.",
    answer: "conservative",
    wrong: ["negligent", "prohibitive", "speculative"],
    why: "The passage says the team preserved rather than altered. *Conservative* here means cautious and preserving, in contrast with *transformative*.",
    difficulty: "hard",
  },
  {
    text: "Field recordings made in the 1930s remain ______ for linguists, since several of the languages captured on them have no living speakers.",
    answer: "invaluable",
    wrong: ["obsolete", "provisional", "conventional"],
    why: "Recordings of languages with no living speakers are irreplaceable. *Invaluable* means extremely valuable.",
    difficulty: "easy",
  },
  {
    text: "The critic's praise was ______: she called the performance the finest she had heard in twenty years and returned the following night to hear it again.",
    answer: "unreserved",
    wrong: ["grudging", "conditional", "perfunctory"],
    why: "The colon shows praise without any qualification. *Unreserved* means given without holding anything back.",
    difficulty: "medium",
  },
  {
    text: "Because the samples had been stored improperly, the laboratory declined to draw any ______ conclusions from the analysis.",
    answer: "definitive",
    wrong: ["preliminary", "collaborative", "quantitative"],
    why: "Improper storage undermines certainty, so the lab avoids conclusions presented as final. *Definitive* means conclusive.",
    difficulty: "medium",
  },
  {
    text: "The engineer's memo was ______, running to a single page that identified the fault, its cause, and the repair.",
    answer: "succinct",
    wrong: ["exhaustive", "equivocal", "digressive"],
    why: "One page covering three points describes compact writing. *Succinct* means briefly and clearly expressed.",
    difficulty: "easy",
  },
  {
    text: "Far from ______ the older theory, the new measurements extend it, showing that it holds under conditions its authors never tested.",
    answer: "supplanting",
    wrong: ["confirming", "clarifying", "summarizing"],
    why: "*Far from ___, the new measurements extend it* requires a word meaning to replace. *Supplanting* means displacing or replacing.",
    difficulty: "hard",
  },
  {
    text: "Roughly a third of the manuscript is ______: water damage has left whole passages that no amount of imaging can recover.",
    answer: "illegible",
    wrong: ["apocryphal", "abridged", "annotated"],
    why: "Water damage that no imaging can recover leaves text that cannot be read. *Illegible* means impossible to read.",
    difficulty: "easy",
  },
  {
    text: "The company's claim that the process is carbon neutral is ______ on an assumption — that the forest will be replanted — that the contract does not actually require.",
    answer: "predicated",
    wrong: ["conferred", "delineated", "administered"],
    why: "The claim rests on an assumption. *Predicated on* means founded or based on.",
    difficulty: "hard",
  },
  {
    text: "Rather than a single author, the text seems to have had several, since its vocabulary and syntax shift ______ between the third and fourth chapters.",
    answer: "abruptly",
    wrong: ["gradually", "predictably", "subtly"],
    why: "A shift sharp enough to indicate a change of author is sudden, not gradual or subtle. *Abruptly* means suddenly.",
    difficulty: "medium",
  },
  {
    text: "The dancer's technique is ______: no motion is wasted, and each gesture resolves cleanly into the next.",
    answer: "economical",
    wrong: ["improvisational", "theatrical", "derivative"],
    why: "No wasted motion describes efficiency of means. *Economical* means using no more than is needed.",
    difficulty: "medium",
  },
  {
    text: "Although the two species look nearly identical, their calls are ______ enough that researchers can tell them apart without ever seeing a bird.",
    answer: "distinct",
    wrong: ["muted", "melodious", "infrequent"],
    why: "Researchers can identify species by call alone, so the calls must be clearly different. *Distinct* means clearly separate or recognizable.",
    difficulty: "easy",
  },
  {
    text: "The proposal was ______ by the very board that had commissioned it, on the grounds that its cost estimates were three years out of date.",
    answer: "rejected",
    wrong: ["endorsed", "amended", "circulated"],
    why: "Out-of-date cost estimates are given as grounds against the proposal, so the board turned it down. *Rejected* fits that outcome.",
    difficulty: "easy",
  },
  {
    text: "Historians once treated the chronicle as ______, but the discovery of an earlier source it copies almost verbatim has forced a reassessment.",
    answer: "original",
    wrong: ["fragmentary", "unreliable", "influential"],
    why: "Finding that it copies an earlier source undermines the belief that it was first-hand. *Original* is the belief the discovery overturns.",
    difficulty: "hard",
  },
  {
    text: "The alloy's resistance to fatigue is ______: after ten million loading cycles the test coupons showed no measurable cracking.",
    answer: "remarkable",
    wrong: ["marginal", "theoretical", "incidental"],
    why: "Ten million cycles with no cracking is an exceptional result, and the colon presents it as evidence. *Remarkable* means worthy of notice.",
    difficulty: "easy",
  },
  {
    text: "Rather than describing the ritual directly, the ethnographer ______ it, letting a sequence of overheard remarks stand in for the ceremony itself.",
    answer: "evokes",
    wrong: ["documents", "prescribes", "refutes"],
    why: "Suggesting the ceremony indirectly through overheard remarks is calling it to mind rather than recording it. *Evokes* means to bring to mind.",
    difficulty: "hard",
  },
  {
    text: "Because the vault has no external power, its cooling is entirely ______ on the surrounding permafrost.",
    answer: "reliant",
    wrong: ["insistent", "adjacent", "restricted"],
    why: "With no external power, the permafrost is what keeps the vault cold. *Reliant on* means dependent on.",
    difficulty: "easy",
  },
  {
    text: "The playwright's dialogue is ______: characters interrupt one another, trail off, and repeat themselves exactly as speakers do outside the theater.",
    answer: "naturalistic",
    wrong: ["stylized", "archaic", "aphoristic"],
    why: "Dialogue that reproduces how people actually speak is lifelike. *Naturalistic* names that quality.",
    difficulty: "medium",
  },
  {
    text: "Efforts to reintroduce the species have been ______ by the same pesticide use that caused the original decline.",
    answer: "thwarted",
    wrong: ["accelerated", "financed", "publicized"],
    why: "The pesticide that caused the decline is now blocking recovery. *Thwarted* means prevented from succeeding.",
    difficulty: "medium",
  },
  {
    text: "The report's tone is ______ throughout: it neither praises the program nor condemns it, presenting outcomes and letting readers judge.",
    answer: "impartial",
    wrong: ["derisive", "laudatory", "urgent"],
    why: "Neither praising nor condemning describes a refusal to take sides. *Impartial* means unbiased.",
    difficulty: "medium",
  },
  {
    text: "Given how little of the settlement has been excavated, any estimate of its population must remain ______.",
    answer: "provisional",
    wrong: ["quantitative", "obligatory", "unanimous"],
    why: "With most of the site unexcavated, estimates are temporary and subject to revision. *Provisional* means tentative.",
    difficulty: "medium",
  },
  {
    text: "Ito's contribution to the field is often ______: because she published under her institution's name rather than her own, credit went elsewhere for decades.",
    answer: "overlooked",
    wrong: ["exaggerated", "disputed", "duplicated"],
    why: "Credit going elsewhere means her role was not noticed. *Overlooked* means failed to be noticed.",
    difficulty: "easy",
  },
  {
    text: "The two accounts are not contradictory but ______: each describes a stage of the process the other passes over.",
    answer: "complementary",
    wrong: ["redundant", "hypothetical", "successive"],
    why: "Each fills in what the other omits, so together they make a whole. *Complementary* means completing one another.",
    difficulty: "hard",
  },
  {
    text: "Rain shadows form when a mountain range ______ moisture from prevailing winds, leaving the leeward slope markedly drier.",
    answer: "strips",
    wrong: ["distributes", "attracts", "conserves"],
    why: "The leeward side is drier because moisture has been removed on the way over. *Strips* means removes.",
    difficulty: "medium",
  },
  {
    text: "The archive's finding aid is ______: it lists box numbers but says nothing about what any box contains.",
    answer: "rudimentary",
    wrong: ["comprehensive", "authoritative", "annotated"],
    why: "Listing only box numbers is the barest possible level of description. *Rudimentary* means basic and undeveloped.",
    difficulty: "hard",
  },
  {
    text: "Early critics dismissed the score as ______, but its harmonic language is now recognized as an anticipation of techniques that would not become common for another thirty years.",
    answer: "incoherent",
    wrong: ["conventional", "derivative", "sentimental"],
    why: "The contrast is between an early dismissal and later recognition of forward-looking harmony. Music too advanced to be understood would be heard as not making sense — *incoherent*.",
    difficulty: "hard",
  },
  {
    text: "Because tidal energy is entirely ______, engineers can schedule maintenance years in advance around the lunar calendar.",
    answer: "predictable",
    wrong: ["renewable", "inexpensive", "sustainable"],
    why: "Scheduling years ahead is possible only because the timing is known in advance. *Predictable* is what supports that scheduling.",
    difficulty: "medium",
  },
  {
    text: "Her prose style is ______ in the best sense: the same three words recur across a chapter, gathering weight each time.",
    answer: "repetitive",
    wrong: ["ornate", "colloquial", "elliptical"],
    why: "Words recurring across a chapter is repetition, which the sentence frames as a virtue. *Repetitive* is the plain description.",
    difficulty: "medium",
  },
  {
    text: "The survey's design ______ households without permanent addresses, a limitation the authors acknowledge in their conclusion.",
    answer: "excludes",
    wrong: ["compensates", "oversamples", "anonymizes"],
    why: "The sentence names a limitation the authors admit: some households are left out. *Excludes* means leaves out.",
    difficulty: "medium",
  },
  {
    text: "What makes the discovery ______ is not the fossil itself but its location: no member of the group had previously been found north of the equator.",
    answer: "significant",
    wrong: ["controversial", "recent", "expensive"],
    why: "An unprecedented location is what gives the find its importance. *Significant* means important.",
    difficulty: "easy",
  },
  {
    text: "The instrument's readings drifted so ______ that a full day of data could be corrected with a single linear adjustment.",
    answer: "steadily",
    wrong: ["erratically", "imperceptibly", "violently"],
    why: "A single linear correction works only if the drift is uniform over time. *Steadily* means at a constant rate.",
    difficulty: "hard",
  },
  {
    text: "Rather than issuing rules, the guild ______ standards through apprenticeship: a technique spread because masters taught it, not because anyone required it.",
    answer: "propagated",
    wrong: ["enforced", "codified", "abandoned"],
    why: "The sentence contrasts requirement with spreading by teaching. *Propagated* means caused to spread.",
    difficulty: "hard",
  },
  {
    text: "Although sold as a luxury good today, saffron was once a ______ ingredient in the region, grown in kitchen gardens and used daily.",
    answer: "commonplace",
    wrong: ["medicinal", "imported", "seasonal"],
    why: "*Although sold as a luxury today* sets up a contrast with the past; grown at home and used daily describes ordinariness. *Commonplace* means ordinary.",
    difficulty: "medium",
  },
  {
    text: "Nunez's argument is ______ on a single reading of the 1873 statute; if that reading fails, nothing else in the article survives.",
    answer: "contingent",
    wrong: ["reflective", "consistent", "incidental"],
    why: "The argument stands or falls with one reading. *Contingent on* means dependent on.",
    difficulty: "hard",
  },
  {
    text: "The eruption's ash layer gives archaeologists an unusually ______ marker: everything below it predates 1628 BCE, and everything above it postdates that year.",
    answer: "precise",
    wrong: ["durable", "extensive", "accessible"],
    why: "A layer that separates before and after to a single year is exact. *Precise* names that exactness.",
    difficulty: "medium",
  },
  {
    text: "Reviewers found the study ______, noting that its 12 participants could not support conclusions about a population of millions.",
    answer: "underpowered",
    wrong: ["unethical", "unreadable", "unoriginal"],
    why: "Twelve participants being too few to support broad conclusions is a criticism of sample size. *Underpowered* is the term for a study too small to detect what it claims.",
    difficulty: "hard",
  },
  {
    text: "The bridge's cables are inspected annually because corrosion, once it begins, ______ far faster in a marine environment than in a dry one.",
    answer: "progresses",
    wrong: ["originates", "reverses", "stabilizes"],
    why: "The comparison is about the speed at which corrosion advances after starting. *Progresses* means advances.",
    difficulty: "easy",
  },
  {
    text: "Rather than a defect, the wobble in the recording is ______: it preserves the sound of the hand-cranked machine on which the performance was captured.",
    answer: "evidence",
    wrong: ["a distraction", "an exaggeration", "a repetition"],
    why: "The wobble shows something about how the recording was made, so it functions as proof rather than a flaw.",
    difficulty: "medium",
    phrase: true,
  },
  {
    text: "The proposal's chief virtue is that it is ______: every step can be carried out with equipment the district already owns.",
    answer: "feasible",
    wrong: ["innovative", "reversible", "temporary"],
    why: "Being achievable with equipment already on hand describes practicality. *Feasible* means able to be done.",
    difficulty: "easy",
  },
  {
    text: "Because the two authors disagree about almost everything else, their ______ on this point carries unusual weight.",
    answer: "agreement",
    wrong: ["silence", "ambivalence", "expertise"],
    why: "The sentence contrasts general disagreement with something notable on this point — their converging judgment.",
    difficulty: "medium",
  },
  {
    text: "Hale's later poems ______ the forms of her early work: the sonnets return, but the rhymes are now deliberately imperfect.",
    answer: "revisit",
    wrong: ["renounce", "obscure", "translate"],
    why: "The sonnets return in altered shape, so the later poems come back to earlier forms. *Revisit* means return to.",
    difficulty: "hard",
  },
  {
    text: "The colony's growth is ______ by the availability of nesting cavities rather than by the food supply, which remains abundant year-round.",
    answer: "constrained",
    wrong: ["accelerated", "measured", "obscured"],
    why: "Nesting cavities, not food, set the limit on growth. *Constrained* means limited.",
    difficulty: "medium",
  },
  {
    text: "Aunt Marguerite's letters are ______ about the family's finances, mentioning money only to say that the subject is not worth discussing.",
    answer: "reticent",
    wrong: ["candid", "exhaustive", "indignant"],
    why: "Mentioning money only to refuse to discuss it is holding back. *Reticent* means reluctant to speak about something.",
    difficulty: "hard",
  },
  {
    text: "The technique is ______ in the sense that it destroys the sample: a fragment can be dated once and only once.",
    answer: "destructive",
    wrong: ["expensive", "inconclusive", "specialized"],
    why: "The colon explains that the sample is consumed by the measurement. *Destructive* is the plain term for that.",
    difficulty: "easy",
  },
  {
    text: "By 1911 the technique had become so ______ among printers in the city that no workshop advertised it as a specialty any longer.",
    answer: "widespread",
    wrong: ["lucrative", "regulated", "refined"],
    why: "No one advertises as a specialty what everyone does, so the technique had become common. *Widespread* means found everywhere.",
    difficulty: "medium",
  },
  {
    text: "The two data sets appear to conflict, but the discrepancy is ______: the instruments were calibrated to different reference standards.",
    answer: "explicable",
    wrong: ["irreducible", "coincidental", "negligible"],
    why: "A stated cause for the discrepancy means it can be accounted for. *Explicable* means able to be explained.",
    difficulty: "hard",
  },
  {
    text: "The choreography is ______ to the music, following each phrase so closely that the dancers seem to produce the sound themselves.",
    answer: "attentive",
    wrong: ["indifferent", "superior", "preliminary"],
    why: "Following each musical phrase closely describes close attention to the score. *Attentive to* means closely responsive to.",
    difficulty: "medium",
  },
  {
    text: "Because the reef's recovery has been so ______, managers have extended the survey interval from one year to five.",
    answer: "gradual",
    wrong: ["abrupt", "controversial", "expensive"],
    why: "Lengthening the interval between surveys makes sense only if change is slow. *Gradual* means happening slowly.",
    difficulty: "easy",
  },
  {
    text: "Ochoa's monograph is ______: it takes up a single lithograph and devotes three hundred pages to it.",
    answer: "narrow but deep",
    wrong: ["broad and general", "brief and preliminary", "collaborative and interdisciplinary"],
    why: "Three hundred pages on one lithograph is an extremely limited subject treated exhaustively.",
    difficulty: "medium",
    phrase: true,
  },
  {
    text: "The measure passed only after supporters agreed to ______ its most contested provision, which was struck from the final text entirely.",
    answer: "drop",
    wrong: ["strengthen", "clarify", "publicize"],
    why: "The provision was struck from the text, so supporters gave it up. *Drop* means remove.",
    difficulty: "easy",
  },
  {
    text: "Although each observation on its own is ______, together the twelve of them make a case that is difficult to dismiss.",
    answer: "inconclusive",
    wrong: ["erroneous", "expensive", "unpublished"],
    why: "*Although ... on its own ... together they make a strong case* requires a word meaning individually insufficient. *Inconclusive* fits.",
    difficulty: "medium",
  },
  {
    text: "The building's ______ is deceptive: what looks from the street like a single storey opens into four levels cut into the hillside behind.",
    answer: "modesty",
    wrong: ["symmetry", "antiquity", "durability"],
    why: "The street view understates the building's size, so the blank names an appearance of smallness. *Modesty* fits.",
    difficulty: "hard",
  },
  {
    text: "Kwan's method ______ the need for a reference sample entirely, which is why it can be used on objects too valuable to cut.",
    answer: "obviates",
    wrong: ["magnifies", "documents", "postpones"],
    why: "The method works without cutting a sample, so it removes the need for one. *Obviates* means makes unnecessary.",
    difficulty: "hard",
  },
  {
    text: "The results were ______ across all four sites, which is why the team was confident reporting a single figure rather than a range.",
    answer: "consistent",
    wrong: ["provisional", "unexpected", "anonymous"],
    why: "Reporting one figure rather than a range is justified when results agree everywhere. *Consistent* means in agreement.",
    difficulty: "easy",
  },
  {
    text: "The film's pacing is ______: long stretches of stillness are broken by sequences edited so quickly that individual shots are hard to register.",
    answer: "uneven",
    wrong: ["languid", "conventional", "understated"],
    why: "Alternating stillness and very fast cutting describes inconsistency in tempo. *Uneven* names that.",
    difficulty: "medium",
  },
  {
    text: "Because the two populations have been ______ for more than a million years, they no longer interbreed even where their ranges overlap.",
    answer: "isolated",
    wrong: ["migratory", "endangered", "monitored"],
    why: "A long separation is what leads to reproductive incompatibility. *Isolated* means kept apart.",
    difficulty: "medium",
  },
  {
    text: "The essay's argument is ______ rather than original: Bhatt is restating a position first advanced in the 1950s, though more clearly than anyone before her.",
    answer: "synthetic",
    wrong: ["fallacious", "polemical", "autobiographical"],
    why: "Restating and clarifying an existing position is drawing material together rather than inventing it. *Synthetic* means combining existing elements.",
    difficulty: "hard",
  },
  {
    text: "Coastal fog is ______ to the redwoods: the trees absorb it directly through their needles during the dry summer months.",
    answer: "essential",
    wrong: ["detrimental", "invisible", "seasonal"],
    why: "Fog is the trees' summer water source, so they depend on it. *Essential* means absolutely necessary.",
    difficulty: "easy",
  },
  {
    text: "Wei's account is ______ by his own admission: he arrived three days after the events he describes and relied on what others told him.",
    answer: "secondhand",
    wrong: ["exaggerated", "confidential", "contemporaneous"],
    why: "Arriving afterward and relying on others' reports makes the account indirect. *Secondhand* means obtained from others rather than witnessed.",
    difficulty: "medium",
  },
];

export const VOCAB_TEMPLATE: Template = {
  ...base,
  id: "rw-cs-vocab",
  subdomain: "Words in Context",
  skills: ["Words in context", "Contextual vocabulary"],
  difficulty: "medium",
  variants: SEEDS.length,
  build(rng: Rng, index: number): ItemBody {
    const seed = SEEDS[index % SEEDS.length];
    const { choices, correct } = buildChoices(rng, seed.answer, seed.wrong, { sortNumeric: false });
    return {
      stimulus: { type: "passage", paragraphs: [seed.text.replace(/______/g, "______")] },
      prompt: seed.phrase
        ? "Which choice completes the text with the most logical and precise phrase?"
        : "Which choice completes the text with the most logical and precise word or phrase?",
      answerFormat: "multiple-choice",
      choices,
      correct,
      explanation: seed.why,
      difficulty: seed.difficulty,
    };
  },
};
